### ISSUE TITLE
words in UDR on gateway

### ISSUE THREAD

**Issue by khensler** [dmauser/azure-expressroute#1]
https://github.com/dmauser/azure-expressroute/tree/main/er-to-er-transit/ars#udr-requirement-on-gatewaysubnet

"This solution requires that n UDR is created on the GatewaySubnet to steer the traffic to the NVA in the Azure Hub."

Should this be "requires than a UDR"?

**Comment by dmauser** [comment]
Thanks for caching it! I have fix it.
